In [1]:
import pandas
from event_stream import EventStream
dataset = pandas.read_csv('data_test_task.csv')
dataset

,event_timestamp,user_id,screen_width,os,event_name,device,utm_source,utm_medium,page
0,2020-06-23 00:00:00,0c8effba-26db-4f88-8545-02c57befaeb1,375,iOS,tracker_created,mobile,NaN,NaN,/catalog/toys/5198424819474965901/
1,2020-06-23 00:00:00,32002994-9cac-406e-8d37-a2cab1c55e20,393,Android,tracker_created,mobile,NaN,NaN,/catalog/toys/6779096104152160036/
2,2020-06-23 00:00:00,ac166f21-57a4-4465-8ae9-19f22dc33d86,360,Android,tracker_created,mobile,NaN,NaN,/special-offers/
3,2020-06-23 00:00:03,f0bde4f4-6cdc-4d7c-8bb5-51ad8c8633e1,1324,Mac OS X,tracker_created,desktop,NaN,NaN,/catalog/trips/7328958554906710727/
4,2020-06-23 00:00:06,0c8effba-26db-4f88-8545-02c57befaeb1,375,iOS,link_click,mobile,NaN,NaN,/catalog/toys/5198424819474965901/
...,...,...,...,...,...,...,...,...,...
199,2020-06-23 00:03:33,0c8effba-26db-4f88-8545-02c57befaeb1,375,iOS,link_click,mobile,NaN,NaN,/catalog/toys/8130181685261167309/
200,2020-06-23 00:03:33,43af211a-3877-4bc8-8029-2e9874a0c9bb,1920,Windows,button_click,desktop,NaN,NaN,/catalog/toys/2181336604232773912/
201,2020-06-23 00:03:34,43af211a-3877-4bc8-8029-2e9874a0c9bb,1920,Windows,button_click,desktop,NaN,NaN,/catalog/toys/2181336604232773912/
202,2020-06-23 00:03:34,43af211a-3877-4bc8-8029-2e9874a0c9bb,1920,Windows,button_click,desktop,NaN,NaN,/catalog/toys/2181336604232773912/
203,2020-06-23 00:03:35,43af211a-3877-4bc8-8029-2e9874a0c9bb,1920,Windows,button_click,desktop,NaN,NaN,/catalog/toys/2181336604232773912/

In [2]:
event_handler = EventStream(dataframe=dataset,
                            source_data_scheme=('event_timestamp', 'user_id', 'screen_width', 'os', 'event_name', 'device', 'utm_source', 'utm_medium'),
                            final_data_scheme={'user_id', 'event_name', 'event_timestamp'})
print(event_handler)

('event_timestamp', 'user_id', 'screen_width', 'os', 'event_name', 'device', 'utm_source', 'utm_medium') to {'user_id', 'event_name', 'event_timestamp'};
       screen_width
count    204.000000
mean    1597.308824
std      603.214768
min      360.000000
25%     1744.000000
50%     1920.000000
75%     1920.000000
max     1920.000000

In [3]:
map = {
    'condition': {
        'event_name': 'tracker_created',
        'page': '/catalog/'
    },
    'result': {
        'name of something': 1,
        'namespace': "wsda"
    }
}
event_handler.mapping(map)
event_handler.get_dataframe()

,name of something,user_id,event_timestamp,event_name,namespace
0,1,0c8effba-26db-4f88-8545-02c57befaeb1,2020-06-23 00:00:00,tracker_created,wsda
1,1,32002994-9cac-406e-8d37-a2cab1c55e20,2020-06-23 00:00:00,tracker_created,wsda
2,None,ac166f21-57a4-4465-8ae9-19f22dc33d86,2020-06-23 00:00:00,tracker_created,None
3,1,f0bde4f4-6cdc-4d7c-8bb5-51ad8c8633e1,2020-06-23 00:00:03,tracker_created,wsda
4,None,0c8effba-26db-4f88-8545-02c57befaeb1,2020-06-23 00:00:06,link_click,None
...,...,...,...,...,...
199,None,0c8effba-26db-4f88-8545-02c57befaeb1,2020-06-23 00:03:33,link_click,None
200,None,43af211a-3877-4bc8-8029-2e9874a0c9bb,2020-06-23 00:03:33,button_click,None
201,None,43af211a-3877-4bc8-8029-2e9874a0c9bb,2020-06-23 00:03:34,button_click,None
202,None,43af211a-3877-4bc8-8029-2e9874a0c9bb,2020-06-23 00:03:34,button_click,None
203,None,43af211a-3877-4bc8-8029-2e9874a0c9bb,2020-06-23 00:03:35,button_click,None

In [4]:
event_handler.soft_delete(1)

,name of something,user_id,event_timestamp,event_name,namespace
0,1,0c8effba-26db-4f88-8545-02c57befaeb1,2020-06-23 00:00:00,tracker_created,wsda
2,None,ac166f21-57a4-4465-8ae9-19f22dc33d86,2020-06-23 00:00:00,tracker_created,None
3,1,f0bde4f4-6cdc-4d7c-8bb5-51ad8c8633e1,2020-06-23 00:00:03,tracker_created,wsda
4,None,0c8effba-26db-4f88-8545-02c57befaeb1,2020-06-23 00:00:06,link_click,None
5,1,0c8effba-26db-4f88-8545-02c57befaeb1,2020-06-23 00:00:07,tracker_created,wsda
...,...,...,...,...,...
199,None,0c8effba-26db-4f88-8545-02c57befaeb1,2020-06-23 00:03:33,link_click,None
200,None,43af211a-3877-4bc8-8029-2e9874a0c9bb,2020-06-23 00:03:33,button_click,None
201,None,43af211a-3877-4bc8-8029-2e9874a0c9bb,2020-06-23 00:03:34,button_click,None
202,None,43af211a-3877-4bc8-8029-2e9874a0c9bb,2020-06-23 00:03:34,button_click,None
203,None,43af211a-3877-4bc8-8029-2e9874a0c9bb,2020-06-23 00:03:35,button_click,None

In [5]:
event_handler.soft_delete([2, 5, 7])

,name of something,user_id,event_timestamp,event_name,namespace
0,1,0c8effba-26db-4f88-8545-02c57befaeb1,2020-06-23 00:00:00,tracker_created,wsda
3,1,f0bde4f4-6cdc-4d7c-8bb5-51ad8c8633e1,2020-06-23 00:00:03,tracker_created,wsda
4,None,0c8effba-26db-4f88-8545-02c57befaeb1,2020-06-23 00:00:06,link_click,None
6,None,43af211a-3877-4bc8-8029-2e9874a0c9bb,2020-06-23 00:00:13,button_click,None
8,1,0c8effba-26db-4f88-8545-02c57befaeb1,2020-06-23 00:00:19,tracker_created,wsda
...,...,...,...,...,...
199,None,0c8effba-26db-4f88-8545-02c57befaeb1,2020-06-23 00:03:33,link_click,None
200,None,43af211a-3877-4bc8-8029-2e9874a0c9bb,2020-06-23 00:03:33,button_click,None
201,None,43af211a-3877-4bc8-8029-2e9874a0c9bb,2020-06-23 00:03:34,button_click,None
202,None,43af211a-3877-4bc8-8029-2e9874a0c9bb,2020-06-23 00:03:34,button_click,None
203,None,43af211a-3877-4bc8-8029-2e9874a0c9bb,2020-06-23 00:03:35,button_click,None